/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for aggregated LLM metadata and provider information
 */
export interface LLMStats {
  [k: string]: {
    /**
     * ID of the main version of this model
     */
    canonical_model_id?: string | null;
    /**
     * ID of the base model if fine-tuned
     */
    fine_tuned_from_model_id?: string | null;
    /**
     * Human-readable name of the model
     */
    name: string;
    /**
     * Description of model capabilities
     */
    description: string;
    /**
     * Release date of the model
     */
    release_date: string;
    /**
     * Maximum input tokens
     */
    input_context_size: number;
    /**
     * Maximum output tokens
     */
    output_context_size: number;
    /**
     * Model license
     */
    license: string;
    /**
     * Whether model handles multiple modalities
     */
    multimodal: boolean;
    /**
     * Whether model has web access
     */
    web_hydrated: boolean;
    /**
     * Training data cutoff date
     */
    knowledge_cutoff?: string | null;
    /**
     * API documentation link
     */
    api_ref_link: string;
    /**
     * Interactive playground link
     */
    playground_link?: string | null;
    /**
     * Research paper link
     */
    paper_link?: string | null;
    /**
     * Announcement blog link
     */
    scorecard_blog_link?: string | null;
    /**
     * Source code repository link
     */
    repo_link?: string | null;
    /**
     * Model weights link
     */
    weights_link?: string | null;
    /**
     * Number of model parameters
     */
    param_count?: number | null;
    /**
     * Number of training tokens
     */
    training_tokens?: number | null;
    qualitative_metrics?: {
      dataset_name: string;
      score: number;
      is_self_reported: boolean;
      analysis_method: string;
      date_recorded: string;
      source_link: string;
      [k: string]: unknown;
    }[];
    providers: {
      provider_name: string;
      provider_website: string;
      price_per_input_token: number;
      price_per_output_token: number;
      throughput: number;
      latency: number;
      updated_at: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
}
