/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface QuestionPool {
  license_class: "technician" | "general" | "extra";
  version: string;
  group_titles: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[TGE][0-9][A-Z]$".
     */
    [k: string]: string;
  };
  questions: {
    id: string;
    group: string;
    question: string;
    /**
     * @minItems 4
     * @maxItems 4
     */
    answers: [
      {
        option: "A" | "B" | "C" | "D";
        text: string;
        [k: string]: unknown;
      },
      {
        option: "A" | "B" | "C" | "D";
        text: string;
        [k: string]: unknown;
      },
      {
        option: "A" | "B" | "C" | "D";
        text: string;
        [k: string]: unknown;
      },
      {
        option: "A" | "B" | "C" | "D";
        text: string;
        [k: string]: unknown;
      }
    ];
    correct_answer: "A" | "B" | "C" | "D";
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
