module.exports = {
  bannerComment: `/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run 'npm run generate:types' to regenerate this file.
 */`,
  cwd: '../schema',
  style: {
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 100
  }
};
